runtime: nodejs18 # or another supported version
env: standard
instance_class: F1

env_variables:
  MODB_URL: mongodb+srv://antraAngular:jVoARhjqNU6GtZQG@cluster0.uqd3b.mongodb.net/user
  JWT_SECRET: 7%Z%$>_N8N-@@{VE/na6'U_mM@g[4WF}T%-n{JK_&:(AgT(SMgQ}-U)%h*8U_j\?
  TOKEN_EXP: 1800
